const genericTasks = [
    "Spot someone wearing red",
    "Hear a famous quote",
    "See a character running",
    "Notice a dramatic pause",
    "Spot a vehicle chase",
    "Identify a funny moment",
    "See a character eating",
    "Spot a background character smiling",
    "Notice a unique hairstyle",
    "Spot a character reading a book",
    "See a coffee cup in a scene",
    "Notice someone wearing sunglasses",
    "Spot a building collapse",
    "Hear a loud scream",
    "Spot a character using a gadget",
    "See a sunset or sunrise",
    "Spot a handshake",
    "Notice someone dancing",
    "Spot a crying character",
    "See a character driving",
    "Notice a slow-motion scene",
    "Hear a joke or pun",
    "Spot an animal in the scene",
    "Notice a character pointing",
    "Spot a character holding a drink",
  ];

export default genericTasks;